export const FLAG_TOGGLING_SHOW_QR_CODE = 'FLAG_TOGGLING_SHOW_QR_CODE';
export const TOGGLE_SHOW_QR_CODE_SUCCEEDED = 'TOGGLE_SHOW_QR_CODE_SUCCEEDED';
export const TOGGLE_SHOW_QR_CODE_FAILED = 'TOGGLE_SHOW_QR_CODE_FAILED';
export const FLAG_TOGGLING_SHOW_MODEL = 'FLAG_TOGGLING_SHOW_MODEL';
export const TOGGLE_SHOW_MODEL_SUCCEEDED = 'TOGGLE_SHOW_MODEL_SUCCEEDED';
export const TOGGLE_SHOW_MODEL_FAILED = 'TOGGLE_SHOW_MODEL_FAILED';
